name: Set Up, Build, and Push
on: [workflow_dispatch]
jobs:
  install_test_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        make install
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
  build_and_push:
    needs: install_test_format # Only run if previous job is successful
    runs-on: ubuntu-latest
    steps:
      # Checks out repo under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v3
      # Tooling for building Docker images
      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v1
      # All credentials are already provided
      - name: Login to Github container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      # Adhere to constraint for publishing container
      # Two commas is for parameter expansion for all lowercase
      # Format of GITHUB_REPOSITORY: username/repo name
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      # Uses commit hash for the image tag
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

